# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RetailAttendanceMonitor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RetailAttendanceMonitor
  pod "HockeySDK", :subspecs => ['AllFeaturesLib']

  target 'RetailAttendanceMonitorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
#
# target 'RetailAttendanceMonitor-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!
#
#   # Pods for RetailAttendanceMonitor-tvOS
#
#   target 'RetailAttendanceMonitor-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
#
# end
